version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker/password
    DOCKER_REGISTRY_URL: /myapp/docker/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo $IMAGE_TAG
      - echo "Running tests..."
      - cd simple-python-app/
      - echo "Building Docker image..."
      - docker build -t  521992171924.dkr.ecr.us-east-1.amazonaws.com/${project}/${component}:$IMAGE_TAG .
      - echo aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 521992171924.dkr.ecr.us-east-1.amazonaws.com
      - docker push 521992171924.dkr.ecr.us-east-1.amazonaws.com/${project}/${component}:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app

